# Generated by Django 2.2.6 on 2019-11-08 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationFormData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('phone', models.IntegerField()),
                ('dob', models.DateField()),
                ('institution', models.CharField(max_length=100)),
                ('mun_exp', models.CharField(max_length=100)),
                ('council_p1', models.CharField(max_length=100)),
                ('council_p2', models.CharField(max_length=100)),
                ('imp_p1', models.CharField(max_length=1500)),
                ('q1', models.CharField(max_length=5000)),
                ('q2', models.CharField(max_length=5000)),
                ('accommodation', models.CharField(max_length=100)),
                ('cv', models.FileField(upload_to='')),
            ],
        ),
    ]
