# Generated by Django 2.2.6 on 2019-11-08 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mun_forms', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicationformdata',
            name='cv',
        ),
    ]
